language: node_js
node_js:
  - "node"

after_script:
  - npm run build
  - cd ./dist
  - git init
  - git config user.name "${woshitiancai1}"
  - git config user.email "${2590919679@qq.com}"
  - git add .
  - git commit -m "publish wet site"
  - git push --force --quiet "https://${xuemingxing2}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
© 2020 GitHub, Inc.